
# Site settings
name: kentlee2.github.io
email: luoyan35714@126.com
author: kentlee2
url: 
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/luoyan35714/
port: 3333
baseurl: ""
description: Actually, less is more!
meta_description: åº·å¿—å?ä¸ªäººåšå®¢;å­¦è€Œä¸æ€åˆ™ç½?æ€è€Œä¸å­¦åˆ™æ®?ç”Ÿå‘½ä¸æ­¢;æŠ˜è…¾ä¸ä¼‘
motto: It's our wits that make us men.
banner: å­¦è€Œä¸æ€åˆ™ç½”ï¼Œæ€è€Œä¸å­¦åˆ™æ®†ã€?
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light